server:
  port: 2525

spring:
   datasource:
     url: jdbc:postgresql://localhost:5432/postgres
     password: root123
     username: postgres

   jpa:
     generate-ddl: true
     hibernate:
       ddl-auto: none
     show-sql: true

app:
  save-file-path: C:\Users\mirkomil_a\saved

springdoc:
  packages-to-scan: com.example.controller
  swagger-ui:
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: true